model_seeds:
  alexnet:
    - 1
    - 2
    - 3
    - 4
    - 5
  resnet50:
    - 1
    - 2
    - 3
    - 4
    - 5
  #it_b_16:
   # - 'torchvision_IMAGENET1K_V1'


models:
  alexnet: #select all feature layers
    'features.0': 'Conv1'
    'features.1': 'Relu1'
    'features.2': 'MaxPool1'
    'features.3': 'Conv2'
    'features.4': 'Relu2'
    'features.5': 'MaxPool2'
    'features.6': 'Conv3'
    'features.7': 'Relu3'
    'features.8': 'Conv4'
    'features.9': 'Relu4'
    'features.10': 'Conv5'
    'features.11': 'Relu5'
    'features.12': 'MaxPool5'
    'avgpool' : 'AvgPool'
    'classifier.0': 'Dropout'
    'classifier.1': 'FullyConnected1'
    'classifier.2': 'Relu6'
    'classifier.3': 'Dropout2'
    'classifier.4': 'FullyConnected2'
    'classifier.5': 'Relu7'
    'classifier.6': 'FullyConnected3'
  resnet50:
    'conv1': 'conv1'
    'bn1': 'bn1'
    'relu': 'relu'
    'maxpool': 'maxpool'
    'layer1.0': 'layer1.0'
    'layer1.0.conv1': 'layer1.0.conv1'
    'layer1.0.bn1': 'layer1.0.bn1'
    'layer1.0.conv2': 'layer1.0.conv2'
    'layer1.0.bn2': 'layer1.0.bn2'
    'layer1.0.conv3': 'layer1.0.conv3'
    'layer1.0.bn3': 'layer1.0.bn3'
    'layer1.0.relu': 'layer1.0.relu'
    'layer1.0.downsample': 'layer1.0.downsample'
    'layer1.0.downsample.0': 'layer1.0.downsample.0'
    #'layer1.0.downsample.1': 'layer1.0.downsample.1' 
    'layer1.1': 'layer1.1'
    'layer1.1.conv1': 'layer1.1.conv1'
    'layer1.1.bn1': 'layer1.1.bn1'
    'layer1.1.conv2': 'layer1.1.conv2'
    'layer1.1.bn2': 'layer1.1.bn2'
    'layer1.1.conv3': 'layer1.1.conv3'
    'layer1.1.bn3': 'layer1.1.bn3'
    'layer1.1.relu': 'layer1.1.relu'
    'layer1.2': 'layer1.2'
    'layer1.2.conv1': 'layer1.2.conv1'
    'layer1.2.bn1': 'layer1.2.bn1'
    'layer1.2.conv2': 'layer1.2.conv2'
    'layer1.2.bn2': 'layer1.2.bn2'
    'layer1.2.conv3': 'layer1.2.conv3'
    'layer1.2.bn3': 'layer1.2.bn3'
    'layer1.2.relu': 'layer1.2.relu'
    'layer2.0': 'layer2.0'
    'layer2.0.conv1': 'layer2.0.conv1'
    'layer2.0.bn1': 'layer2.0.bn1'
    'layer2.0.conv2': 'layer2.0.conv2'
    'layer2.0.bn2': 'layer2.0.bn2'
    'layer2.0.conv3': 'layer2.0.conv3'
    'layer2.0.bn3': 'layer2.0.bn3'
    'layer2.0.relu': 'layer2.0.relu'
    'layer2.0.downsample': 'layer2.0.downsample'
    'layer2.0.downsample.0': 'layer2.0.downsample.0'
    #'layer2.0.downsample.1': 'layer2.0.downsample.1' 
    'layer2.1': 'layer2.1'
    'layer2.1.conv1': 'layer2.1.conv1'
    'layer2.1.bn1': 'layer2.1.bn1'
    'layer2.1.conv2': 'layer2.1.conv2'
    'layer2.1.bn2': 'layer2.1.bn2'
    'layer2.1.conv3': 'layer2.1.conv3'
    'layer2.1.bn3': 'layer2.1.bn3'
    'layer2.1.relu': 'layer2.1.relu'
    'layer2.2': 'layer2.2'
    'layer2.2.conv1': 'layer2.2.conv1'
    'layer2.2.bn1': 'layer2.2.bn1'
    'layer2.2.conv2': 'layer2.2.conv2'
    'layer2.2.bn2': 'layer2.2.bn2'
    'layer2.2.conv3': 'layer2.2.conv3'
    'layer2.2.bn3': 'layer2.2.bn3'
    'layer2.2.relu': 'layer2.2.relu'
    'layer2.3': 'layer2.3'
    'layer2.3.conv1': 'layer2.3.conv1'
    'layer2.3.bn1': 'layer2.3.bn1'
    'layer2.3.conv2': 'layer2.3.conv2'
    'layer2.3.bn2': 'layer2.3.bn2'
    'layer2.3.conv3': 'layer2.3.conv3'
    'layer2.3.bn3': 'layer2.3.bn3'
    'layer2.3.relu': 'layer2.3.relu'
    'layer3.0': 'layer3.0'
    'layer3.0.conv1': 'layer3.0.conv1'
    'layer3.0.bn1': 'layer3.0.bn1'
    'layer3.0.conv2': 'layer3.0.conv2'
    'layer3.0.bn2': 'layer3.0.bn2'
    'layer3.0.conv3': 'layer3.0.conv3'
    'layer3.0.bn3': 'layer3.0.bn3'
    'layer3.0.relu': 'layer3.0.relu'
    'layer3.0.downsample': 'layer3.0.downsample'
    'layer3.0.downsample.0': 'layer3.0.downsample.0'
    #'layer3.0.downsample.1': 'layer3.0.downsample.1' 
    'layer3.1': 'layer3.1'
    'layer3.1.conv1': 'layer3.1.conv1'
    'layer3.1.bn1': 'layer3.1.bn1'
    'layer3.1.conv2': 'layer3.1.conv2'
    'layer3.1.bn2': 'layer3.1.bn2'
    'layer3.1.conv3': 'layer3.1.conv3'
    'layer3.1.bn3': 'layer3.1.bn3'
    'layer3.1.relu': 'layer3.1.relu'
    'layer3.2': 'layer3.2'
    'layer3.2.conv1': 'layer3.2.conv1'
    'layer3.2.bn1': 'layer3.2.bn1'
    'layer3.2.conv2': 'layer3.2.conv2'
    'layer3.2.bn2': 'layer3.2.bn2'
    'layer3.2.conv3': 'layer3.2.conv3'
    'layer3.2.bn3': 'layer3.2.bn3'
    'layer3.2.relu': 'layer3.2.relu'
    'layer3.3': 'layer3.3'
    'layer3.3.conv1': 'layer3.3.conv1'
    'layer3.3.bn1': 'layer3.3.bn1'
    'layer3.3.conv2': 'layer3.3.conv2'
    'layer3.3.bn2': 'layer3.3.bn2'
    'layer3.3.conv3': 'layer3.3.conv3'
    'layer3.3.bn3': 'layer3.3.bn3'
    'layer3.3.relu': 'layer3.3.relu'
    'layer3.4': 'layer3.4'
    'layer3.4.conv1': 'layer3.4.conv1'
    'layer3.4.bn1': 'layer3.4.bn1'
    'layer3.4.conv2': 'layer3.4.conv2'
    'layer3.4.bn2': 'layer3.4.bn2'
    'layer3.4.conv3': 'layer3.4.conv3'
    'layer3.4.bn3': 'layer3.4.bn3'
    'layer3.4.relu': 'layer3.4.relu'
    'layer3.5': 'layer3.5'
    'layer3.5.conv1': 'layer3.5.conv1'
    'layer3.5.bn1': 'layer3.5.bn1'
    'layer3.5.conv2': 'layer3.5.conv2'
    'layer3.5.bn2': 'layer3.5.bn2'
    'layer3.5.conv3': 'layer3.5.conv3'
    'layer3.5.bn3': 'layer3.5.bn3'
    'layer3.5.relu': 'layer3.5.relu'
    'layer4.0': 'layer4.0'
    'layer4.0.conv1': 'layer4.0.conv1'
    'layer4.0.bn1': 'layer4.0.bn1'
    'layer4.0.conv2': 'layer4.0.conv2'
    'layer4.0.bn2': 'layer4.0.bn2'
    'layer4.0.conv3': 'layer4.0.conv3'
    'layer4.0.bn3': 'layer4.0.bn3'
    'layer4.0.relu': 'layer4.0.relu'
    'layer4.0.downsample': 'layer4.0.downsample'
    'layer4.0.downsample.0': 'layer4.0.downsample.0'
    #'layer4.0.downsample.1': 'layer4.0.downsample.1'
    'layer4.1': 'layer4.1'
    'layer4.1.conv1': 'layer4.1.conv1'
    'layer4.1.bn1': 'layer4.1.bn1'
    'layer4.1.conv2': 'layer4.1.conv2'
    'layer4.1.bn2': 'layer4.1.bn2' 
    'layer4.1.conv3': 'layer4.1.conv3'
    'layer4.1.bn3': 'layer4.1.bn3'
    'layer4.1.relu': 'layer4.1.relu'
    'layer4.2': 'layer4.2'
    'layer4.2.conv1': 'layer4.2.conv1'
    'layer4.2.bn1': 'layer4.2.bn1'
    'layer4.2.conv2': 'layer4.2.conv2'
    'layer4.2.bn2': 'layer4.2.bn2'
    'layer4.2.conv3': 'layer4.2.conv3'
    'layer4.2.bn3': 'layer4.2.bn3'
    'layer4.2.relu': 'layer4.2.relu'
    'avgpool': 'avgpool'
    'fc': 'fc'
  vit_b_16:
    'conv_proj': 'conv_proj'
    'encoder': 'encoder'
    'encoder.dropout': 'encoder.dropout'
    'encoder.layers': 'encoder.layers'

    'encoder.layers.encoder_layer_0': 'layer_0'
    'encoder.layers.encoder_layer_0.ln_1': 'layer_0.ln_1'
    'encoder.layers.encoder_layer_0.self_attention': 'layer_0.self_attention'
    # 'encoder.layers.encoder_layer_0.self_attention.out_proj': 'layer_0.self_attention.out_proj'
    'encoder.layers.encoder_layer_0.dropout': 'layer_0.dropout'
    # 'encoder.layers.encoder_layer_0.ln_2': 'layer_0.ln_2'
    'encoder.layers.encoder_layer_0.mlp': 'layer_0.mlp'
    # 'encoder.layers.encoder_layer_0.mlp.0': 'layer_0.mlp.0'
    # 'encoder.layers.encoder_layer_0.mlp.1': 'layer_0.mlp.1'
    # 'encoder.layers.encoder_layer_0.mlp.2': 'layer_0.mlp.2'
    # 'encoder.layers.encoder_layer_0.mlp.3': 'layer_0.mlp.3'
    # 'encoder.layers.encoder_layer_0.mlp.4': 'layer_0.mlp.4'

    'encoder.layers.encoder_layer_1': 'layer_1'
    'encoder.layers.encoder_layer_1.ln_1': 'layer_1.ln_1'
    'encoder.layers.encoder_layer_1.self_attention': 'layer_1.self_attention'
    # 'encoder.layers.encoder_layer_1.self_attention.out_proj': 'layer_1.self_attention.out_proj'
    'encoder.layers.encoder_layer_1.dropout': 'layer_1.dropout'
    # 'encoder.layers.encoder_layer_1.ln_2': 'layer_1.ln_2'
    'encoder.layers.encoder_layer_1.mlp': 'layer_1.mlp'
    # 'encoder.layers.encoder_layer_1.mlp.0': 'layer_1.mlp.0'
    # 'encoder.layers.encoder_layer_1.mlp.1': 'layer_1.mlp.1'
    # 'encoder.layers.encoder_layer_1.mlp.2': 'layer_1.mlp.2'
    # 'encoder.layers.encoder_layer_1.mlp.3': 'layer_1.mlp.3'
    # 'encoder.layers.encoder_layer_1.mlp.4': 'layer_1.mlp.4'
    'encoder.layers.encoder_layer_2': 'layer_2'
    'encoder.layers.encoder_layer_2.ln_1': 'layer_2.ln_1'
    'encoder.layers.encoder_layer_2.self_attention': 'layer_2.self_attention'
    # 'encoder.layers.encoder_layer_2.self_attention.out_proj': 'layer_2.self_attention.out_proj'
    'encoder.layers.encoder_layer_2.dropout': 'layer_2.dropout'
    # 'encoder.layers.encoder_layer_2.ln_2': 'layer_2.ln_2'
    'encoder.layers.encoder_layer_2.mlp': 'layer_2.mlp'
    # 'encoder.layers.encoder_layer_2.mlp.0': 'layer_2.mlp.0'
    # 'encoder.layers.encoder_layer_2.mlp.1': 'layer_2.mlp.1'
    # 'encoder.layers.encoder_layer_2.mlp.2': 'layer_2.mlp.2'
    # 'encoder.layers.encoder_layer_2.mlp.3': 'layer_2.mlp.3'
    # 'encoder.layers.encoder_layer_2.mlp.4': 'layer_2.mlp.4'
    
    'encoder.layers.encoder_layer_3': 'layer_3'
    'encoder.layers.encoder_layer_3.ln_1': 'layer_3.ln_1'
    'encoder.layers.encoder_layer_3.self_attention': 'layer_3.self_attention'
    # 'encoder.layers.encoder_layer_3.self_attention.out_proj': 'layer_3.self_attention.out_proj'
    'encoder.layers.encoder_layer_3.dropout': 'layer_3.dropout'
    # 'encoder.layers.encoder_layer_3.ln_2': 'layer_3.ln_2'
    'encoder.layers.encoder_layer_3.mlp': 'layer_3.mlp'
    # 'encoder.layers.encoder_layer_3.mlp.0': 'layer_3.mlp.0'
    # 'encoder.layers.encoder_layer_3.mlp.1': 'layer_3.mlp.1'
    # 'encoder.layers.encoder_layer_3.mlp.2': 'layer_3.mlp.2'
    # 'encoder.layers.encoder_layer_3.mlp.3': 'layer_3.mlp.3'
    # 'encoder.layers.encoder_layer_3.mlp.4': 'layer_3.mlp.4'

    'encoder.layers.encoder_layer_4': 'layer_4'
    'encoder.layers.encoder_layer_4.ln_1': 'layer_4.ln_1'
    'encoder.layers.encoder_layer_4.self_attention': 'layer_4.self_attention'
    # 'encoder.layers.encoder_layer_4.self_attention.out_proj': 'layer_4.self_attention.out_proj'
    'encoder.layers.encoder_layer_4.dropout': 'layer_4.dropout'
    # 'encoder.layers.encoder_layer_4.ln_2': 'layer_4.ln_2'
    'encoder.layers.encoder_layer_4.mlp': 'layer_4.mlp'
    # 'encoder.layers.encoder_layer_4.mlp.0': 'layer_4.mlp.0'
    # 'encoder.layers.encoder_layer_4.mlp.1': 'layer_4.mlp.1'
    # 'encoder.layers.encoder_layer_4.mlp.2': 'layer_4.mlp.2'
    # 'encoder.layers.encoder_layer_4.mlp.3': 'layer_4.mlp.3'
    # 'encoder.layers.encoder_layer_4.mlp.4': 'layer_4.mlp.4'

    'encoder.layers.encoder_layer_5': 'layer_5'
    'encoder.layers.encoder_layer_5.ln_1': 'layer_5.ln_1'
    'encoder.layers.encoder_layer_5.self_attention': 'layer_5.self_attention'
    # 'encoder.layers.encoder_layer_5.self_attention.out_proj': 'layer_5.self_attention.out_proj'
    'encoder.layers.encoder_layer_5.dropout': 'layer_5.dropout'
    # 'encoder.layers.encoder_layer_5.ln_2': 'layer_5.ln_2'
    'encoder.layers.encoder_layer_5.mlp': 'layer_5.mlp'
    # 'encoder.layers.encoder_layer_5.mlp.0': 'layer_5.mlp.0'
    # 'encoder.layers.encoder_layer_5.mlp.1': 'layer_5.mlp.1'
    # 'encoder.layers.encoder_layer_5.mlp.2': 'layer_5.mlp.2'
    # 'encoder.layers.encoder_layer_5.mlp.3': 'layer_5.mlp.3'
    # 'encoder.layers.encoder_layer_5.mlp.4': 'layer_5.mlp.4'

    'encoder.layers.encoder_layer_6': 'layer_6'
    'encoder.layers.encoder_layer_6.ln_1': 'layer_6.ln_1'
    'encoder.layers.encoder_layer_6.self_attention': 'layer_6.self_attention'
    # 'encoder.layers.encoder_layer_6.self_attention.out_proj': 'layer_6.self_attention.out_proj'
    'encoder.layers.encoder_layer_6.dropout': 'layer_6.dropout'
    # 'encoder.layers.encoder_layer_6.ln_2': 'layer_6.ln_2'
    'encoder.layers.encoder_layer_6.mlp': 'layer_6.mlp'
    # 'encoder.layers.encoder_layer_6.mlp.0': 'layer_6.mlp.0'
    # 'encoder.layers.encoder_layer_6.mlp.1': 'layer_6.mlp.1'
    # 'encoder.layers.encoder_layer_6.mlp.2': 'layer_6.mlp.2'
    # 'encoder.layers.encoder_layer_6.mlp.3': 'layer_6.mlp.3'
    # 'encoder.layers.encoder_layer_6.mlp.4': 'layer_6.mlp.4'
    
    'encoder.layers.encoder_layer_7': 'layer_7'
    'encoder.layers.encoder_layer_7.ln_1': 'layer_7.ln_1'
    'encoder.layers.encoder_layer_7.self_attention': 'layer_7.self_attention'
    # 'encoder.layers.encoder_layer_7.self_attention.out_proj': 'layer_7.self_attention.out_proj'
    'encoder.layers.encoder_layer_7.dropout': 'layer_7.dropout'
    # 'encoder.layers.encoder_layer_7.ln_2': 'layer_7.ln_2'
    'encoder.layers.encoder_layer_7.mlp': 'layer_7.mlp'
    # 'encoder.layers.encoder_layer_7.mlp.0': 'layer_7.mlp.0'
    # 'encoder.layers.encoder_layer_7.mlp.1': 'layer_7.mlp.1'
    # 'encoder.layers.encoder_layer_7.mlp.2': 'layer_7.mlp.2'
    # 'encoder.layers.encoder_layer_7.mlp.3': 'layer_7.mlp.3'
    # 'encoder.layers.encoder_layer_7.mlp.4': 'layer_7.mlp.4'

    'encoder.layers.encoder_layer_8': 'layer_8'
    'encoder.layers.encoder_layer_8.ln_1': 'layer_8.ln_1'
    'encoder.layers.encoder_layer_8.self_attention': 'layer_8.self_attention'
    # 'encoder.layers.encoder_layer_8.self_attention.out_proj': 'layer_8.self_attention.out_proj'
    'encoder.layers.encoder_layer_8.dropout': 'layer_8.dropout'
    # 'encoder.layers.encoder_layer_8.ln_2': 'layer_8.ln_2'
    'encoder.layers.encoder_layer_8.mlp': 'layer_8.mlp'
    # 'encoder.layers.encoder_layer_8.mlp.0': 'layer_8.mlp.0'
    # 'encoder.layers.encoder_layer_8.mlp.1': 'layer_8.mlp.1'
    # 'encoder.layers.encoder_layer_8.mlp.2': 'layer_8.mlp.2'
    # 'encoder.layers.encoder_layer_8.mlp.3': 'layer_8.mlp.3'
    # 'encoder.layers.encoder_layer_8.mlp.4': 'layer_8.mlp.4'

    'encoder.layers.encoder_layer_9': 'layer_9'
    'encoder.layers.encoder_layer_9.ln_1': 'layer_9.ln_1'
    'encoder.layers.encoder_layer_9.self_attention': 'layer_9.self_attention'
    # 'encoder.layers.encoder_layer_9.self_attention.out_proj': 'layer_9.self_attention.out_proj'
    'encoder.layers.encoder_layer_9.dropout': 'layer_9.dropout'
    # 'encoder.layers.encoder_layer_9.ln_2': 'layer_9.ln_2'
    'encoder.layers.encoder_layer_9.mlp': 'layer_9.mlp'
    # 'encoder.layers.encoder_layer_9.mlp.0': 'layer_9.mlp.0'
    # 'encoder.layers.encoder_layer_9.mlp.1': 'layer_9.mlp.1'
    # 'encoder.layers.encoder_layer_9.mlp.2': 'layer_9.mlp.2'
    # 'encoder.layers.encoder_layer_9.mlp.3': 'layer_9.mlp.3'
    # 'encoder.layers.encoder_layer_9.mlp.4': 'layer_9.mlp.4'

    'encoder.layers.encoder_layer_10': 'layer_10'
    'encoder.layers.encoder_layer_10.ln_1': 'layer_10.ln_1'
    'encoder.layers.encoder_layer_10.self_attention': 'layer_10.self_attention'
    # 'encoder.layers.encoder_layer_10.self_attention.out_proj': 'layer_10.self_attention.out_proj'
    'encoder.layers.encoder_layer_10.dropout': 'layer_10.dropout'
    # 'encoder.layers.encoder_layer_10.ln_2': 'layer_10.ln_2'
    'encoder.layers.encoder_layer_10.mlp': 'layer_10.mlp'
    # 'encoder.layers.encoder_layer_10.mlp.0': 'layer_10.mlp.0'
    # 'encoder.layers.encoder_layer_10.mlp.1': 'layer_10.mlp.1'
    # 'encoder.layers.encoder_layer_10.mlp.2': 'layer_10.mlp.2'
    # 'encoder.layers.encoder_layer_10.mlp.3': 'layer_10.mlp.3'
    # 'encoder.layers.encoder_layer_10.mlp.4': 'layer_10.mlp.4'

    'encoder.layers.encoder_layer_11': 'layer_11'
    'encoder.layers.encoder_layer_11.ln_1': 'layer_11.ln_1'
    'encoder.layers.encoder_layer_11.self_attention': 'layer_11.self_attention'
    # 'encoder.layers.encoder_layer_11.self_attention.out_proj': 'layer_11.self_attention.out_proj'
    'encoder.layers.encoder_layer_11.dropout': 'layer_11.dropout'
    # 'encoder.layers.encoder_layer_11.ln_2': 'layer_11.ln_2'
    'encoder.layers.encoder_layer_11.mlp': 'layer_11.mlp'
    # 'encoder.layers.encoder_layer_11.mlp.0': 'layer_11.mlp.0'
    # 'encoder.layers.encoder_layer_11.mlp.1': 'layer_11.mlp.1'
    # 'encoder.layers.encoder_layer_11.mlp.2': 'layer_11.mlp.2'
    # 'encoder.layers.encoder_layer_11.mlp.3': 'layer_11.mlp.3'
    # 'encoder.layers.encoder_layer_11.mlp.4': 'layer_11.mlp.4'
    
    #'encoder.ln': 'encoder.ln'
    'heads': 'heads'
    #'heads.head': 'heads.head'
  
  
 

    
  
modalities:
  ephys:
    - F
    - N
  fmri:
    - "01"
    - "02"
    - "03"
    - "04"
    - "05"
    - "06"
    - "07"
    - "08"
  eeg:
    - "01"
    - "02"
    - "03"
    - "04"
    - "05"
    - "06"
    - "07"
    - "08"
    - "09"
    - "10"
